name: tests
on: [push, pull_request]
defaults:
  run:
    shell: bash
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm install -g runfile.sh
      - run: TEST_RUNFILE=tests/2space/Runfile ./node_modules/.bin/bats --jobs 16 --no-parallelize-across-files tests/test.bats
      - run: TEST_RUNFILE=tests/3space/Runfile ./node_modules/.bin/bats --jobs 16 --no-parallelize-across-files tests/test.bats
      - run: TEST_RUNFILE=tests/4space/Runfile ./node_modules/.bin/bats --jobs 16 --no-parallelize-across-files tests/test.bats
      - run: TEST_RUNFILE=tests/8space/Runfile ./node_modules/.bin/bats --jobs 16 --no-parallelize-across-files tests/test.bats
      - run: TEST_RUNFILE=tests/tabbed/Runfile ./node_modules/.bin/bats --jobs 16 --no-parallelize-across-files tests/test.bats
      - run: TEST_RUNFILE=tests/compact/Runfile ./node_modules/.bin/bats --jobs 16 --no-parallelize-across-files tests/test.bats
